config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :users, only: [:index, :edit, :show, :update]
  resources :books, only: [:index, :edit, :show, :destroy, :create, :update] do
    resources :comments, only: [:destroy, :create]
  end
  # post 'users/:id' => 'users#create'
  get "home/about" => "homes#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  attachment :profile_image

  validates :name, presence: true, length: { maximum: 20, minimum: 2 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @user = current_user
    @book = Book.new

    @books = Book.all
  end

  def new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def show
    @show_book = Book.find(params[:id])
    @book = Book.new
    @comment = Comment.new
    @comment.book_id = @show_book.id
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.book_id = book.id
    if @comment.save
      flash[:notice] = "You have posted comment successfully."
      redirect_to book_path(book)
    else
      @show_book = Book.find(params[:book_id])
      @book = Book.new
      render template: "books/show"
    end
  end

  def destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @book = Book.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    if current_user != @user
      redirect_to user_path(current_user.id)
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books_list.html.erb
<div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table">
        <tr>
            <th>User</th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Comment</th>
        </tr>
        <% books.each do |book| %>
            <tr>
                <td><%= link_to user_path(book.user.id) do %>
                        <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40" %>
                    <% end %>
                </td>
                <td>
                    <%= link_to book_path(book.id) do %>
                        <%= book.title %>
                    <% end %>

                </td>
                <td><%= book.body %></td>
                <td><%= book.comments.count%></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/books/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
            <div>
                <h3>
                    <%= @book.errors.count %> error prohibited this obj from being saved:
                </h3>
                <ul>
                    <% @book.errors.full_messages.each do |message| %>
                        <li>
                            <%= message %>
                        </li>
                    <% end %>
                </ul>

            </div>
        <% end %>
        <%= form_with model: @book, local:true do |f| %>
            <div class="form_group">
                <label for="inputTitle">Title</label>
                <%= f.text_field :title, autofocus: true, id: "inputTitle", placeholder: @book.title, class: "form-control name" %>
            </div>
            <div class="form_group">
                <label for="inputOpinion">Opinion</label>
                <%= f.text_field :body, autofocus: true, id: "inputOpinion", placeholder: @book.body, class: "form-control opinion"  %>
            </div>
            <div class="form_group">
                <%= f.submit "Update Book"%>
            </div>
        <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        <%= link_to "Back", books_path %>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 mt-3">
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= @book.errors.count %> errors prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <%= render '/sidebar', user: @user, book: @book %>
      <%= render 'books/books_list', books: @books %>
    </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 mt-3">
    <div class="row">
      <%= render "/sidebar", user: @show_book.user, book: @book%>
      <div class="col-md-8 offset-md-1">
        <h1>Book detail</h1>
        <table class="table">
          <tr>
            <td>
              <div>
                <%= attachment_image_tag @show_book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg" %>
              </div>
              <%= link_to @show_book.user.name, user_path(@show_book.user.id) %>
            </td>
            <td><%= link_to @show_book.title, book_path(@show_book.id) %></td>
            <td><%= @show_book.body %></td>
            <% if current_user == @show_book.user %>
              <td><%= link_to "Edit", edit_book_path(@show_book.id), class: "btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@show_book.id), method: :delete, class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        </table>
        <h3>Comments</h3>
        <% if @comment.errors.any? %>
          <h4 class="text-danger">error</h4>
          <ul>
            <li><%= @comment.errors.full_messages[0] %></li>
          </ul>
        <% end %>
        <%= form_with model: [@show_book, @comment], local: true do |f| %>
          <div class="form_group">
            <label for="input_comment">
              <%= f.text_area :comment, id: "input_comment", class: "form_control comment" %>
            </label>
          </div>
          <div class="form_group">
            <%= f.submit "Submit Comment"%>
          </div>
        <% end %>
        <table class="table">
          <% @show_book.comments.each do |comment| %>
            <tr>
              <td>
                <div>
                  <%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size: "40x40"  %>
                </div>

                <%= link_to comment.user.name, user_path(comment.user.id) %>
              </td>
              <td><%= comment.created_at%></td>
              <td><%= comment.comment %></td>
            </tr>

          <% end %>
        </table>

      </div>
    </div>
</div>

app/views/homes/about.html.erb
<div class="container mt-3">
    <div class="row">
        <div class="mx-auto">
            <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers!</strong></h1>
        </div>

    </div>

</div>

app/views/homes/top.html.erb
<div class="container">
    <div class="row">
        <div class="mx-auto">
            <h1 class="mt-3">welcome to <i class="fas fa-book"></i>Bookers !!</h1>
            <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
            <p>you can share and exchange your opinions , inpressions , and emotions </p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3"  %>
                </div>
                <div class="row">
                    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
                </div>
            </div>

        </div>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/fdcdec1fce.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-md bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class: "text-light navbar-brand" %>
          <ul class="navbar-nav ml-auto" >
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to " Home", user_path(current_user.id), class: "fas fa-home text-light nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: "fas fa-users text-light nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: "fas fa-book-open text-light nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "fas fa-sign-out-alt text-light nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to " Home", root_path, class: "fas fa-home text-light nav-link nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: "fas fa-link text-light nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus text-light nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt text-light nav-link" %>
              </li class="nav-item">
            <% end %>
          </ul>
        </div>

      </nav>
    </header>
    <main>
      <%= flash[:notice]%>
      
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            CopyRight Infratop.inc
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mx-auto">
    <h1>user info</h1>
    <% if @user.errors.any? %>
      <div>
        <h3>
          <%= @user.errors.count %> error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form_with model:@user, local:true do |f| %>
      <div class="form_group">
        <label for="inputName">name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:@user.name, class: "form-control name"  %>
      </div>
      <div class="form_group">
        <label for="inputImage">image</label>
        <%= f.attachment_field :profile_image, class: "form-control-file"%>
      </div>
      <div class="form_group">
      <label for="inputIntroduction">introduction</label>
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:@user.introduction, class: "form-control introduction"  %>
      </div>
      <div class="form_group">
        <%= f.submit "Update User" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 mt-3">
    <div class="row">
        <%= render '/sidebar', user: @user, book: @book %>
        <div class="col-md-8 offset-md-1">
            <h1>users</h1>
            <table class="table">
                <tr>
                    <th>id</th>
                    <th>image</th>
                    <th>name</th>
                    <th></th>
                </tr>
                <% @users.each do |user| %>
                    <tr>
                        <td><%= user.id %></td>
                        <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:"40x40" %></td>
                        <td><%= user.name %></td>
                        <td><%= link_to "Show", user_path(user.id)%></td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 mt-3">
    <div class="row">
        <%= render '/sidebar', user: @user, book: @book%>
        <%= render 'books/books_list', books: @books %>
    </div>
</div>